package:
  name: dammit
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default').lstrip('v') }}

source:
  path: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}
  skip: True # [py27 or py34]

requirements:
  build:
    # Python dependencies
    - python
    - numpy
    - pandas
    - numexpr >=2.3.1
    - khmer >=2.1
    - sphinx >1.3.1
    - sphinx_rtd_theme >=0.1.9
    - pytest
    - pytest-runner
    - doit >=0.29.0
    - matplotlib
    - shmlast

    # Other
    - infernal
    - hmmer
    - transdecoder ==3.0.1
    - last
    - busco ==3.0.2

  run:
    # Python dependencies
    - python
    - numpy
    - pandas
    - numexpr >=2.3.1
    - khmer >=2.1
    - sphinx >1.3.1
    - sphinx_rtd_theme >=0.1.9
    - pytest
    - pytest-runner
    # After we upgrade to doit.TaskLoader2, we can remove upper pin
    # https://github.com/dib-lab/dammit/issues/239
    - doit >=0.29.0,<0.36.0
    - matplotlib
    - shmlast

    # Other
    - infernal
    - hmmer
    - transdecoder ==3.0.1
    - last
    - busco ==3.0.2
    - parallel
    - bioconductor-seqlogo

test:
  imports:
    #

  commands:
    - dammit -h > /dev/null

about:
  home: http://dib-lab.github.io/dammit/
  license: BSD
  license_file: LICENSE
  summary: simple de novo transcriptome annotator
