site_name: dammit
site_url: http://dib-lab.github.io/dammit
repo_name: dammit
repo_url: https://github.com/dib-lab/dammit
edit_uri: ""

#extra_css: css/custom.css

copyright: 'Copyright &copy; 2020 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis'

# change directory names here
docs_dir: doc
site_dir: site

theme:
  name: material
  # the next 2 lines are required to use the DIB version
#  name: null
#  custom_dir: 'mkdocs-material-dib/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'green'
    accent: 'purple'
  
  # fun logos! see https://material.io/icons/
  icon:
    logo: material/dns

  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  
  features:
    - instant
#    - tabs

# this will add docs/css/custom.css to all your docs
#extra_css:
#  - css/custom.css

# give a title for each page
nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'Installation':
    - 'Requirements': 'system_requirements.md'
    - 'Bioconda': 'install.md'

  - 'Databases':
    - 'Basic Usage': 'database-usage.md'
    - 'About the Databases': 'database-about.md'
    - 'Advanced Database Handling': 'database-advanced.md'

  - 'Tutorial': 'tutorial.md'

  - 'For developers':
    - 'Notes for developers': 'dev_notes.md'
